"""
Central league configuration for new scraper work.

This module is intentionally not wired into the existing scrapers yet. It is a
stable place to define league metadata before building new reusable pipelines.
"""

CURRENT_SEASON = "2526"


LEAGUES = {
    "laliga": {
        "db_liga_id": 1,
        "slug": "laliga",
        "nombre": "LaLiga",
        "pais": "Espana",
        "temporada": CURRENT_SEASON,
        "tipo": "domestic",
        "sofascore_tournament_id": 8,
        "sofascore_season_id": None,
        "transfermarkt_code": "ES1",
        "fbref_name": "ESP-La Liga",
        "reglas_clasificacion": {
            "champions": [1, 2, 3, 4],
            "europa": [5],
            "conference": [6],
            "descenso": [18, 19, 20],
        },
        "aliases_equipos": {},
    },
    "premier-league": {
        "db_liga_id": 24,
        "slug": "premier-league",
        "nombre": "Premier League",
        "pais": "Inglaterra",
        "temporada": CURRENT_SEASON,
        "tipo": "domestic",
        "sofascore_tournament_id": 17,
        "sofascore_season_id": 76986,
        "transfermarkt_code": "GB1",
        "fbref_name": "ENG-Premier League",
        "reglas_clasificacion": {
            "champions": [1, 2, 3, 4, 5],
            "europa": [6],
            "conference": [7],
            "descenso": [18, 19, 20],
        },
        "aliases_equipos": {
            "manchester united": "manchester utd",
            "wolverhampton": "wolves",
            "liverpool": "liverpool fc",
        },
    },
    "bundesliga": {
        "db_liga_id": 25,
        "slug": "bundesliga",
        "nombre": "Bundesliga",
        "pais": "Alemania",
        "temporada": CURRENT_SEASON,
        "tipo": "domestic",
        "sofascore_tournament_id": 35,
        "sofascore_season_id": 77333,
        "transfermarkt_code": "L1",
        "fbref_name": "GER-Bundesliga",
        "reglas_clasificacion": {
            "champions": [1, 2, 3, 4],
            "europa": [5],
            "conference": [6],
            "playoff_descenso": [16],
            "descenso": [17, 18],
        },
        "aliases_equipos": {
            "fc st. pauli": "st pauli",
            "bayern munich": "fc bayern munchen",
            "bayern munchen": "fc bayern munchen",
            "leverkusen": "bayer leverkusen",
            "dortmund": "borussia dortmund",
        },
    },
    "serie-a": {
        "db_liga_id": 26,
        "slug": "serie-a",
        "nombre": "Serie A",
        "pais": "Italia",
        "temporada": CURRENT_SEASON,
        "tipo": "domestic",
        "sofascore_tournament_id": 23,
        "sofascore_season_id": None,
        "transfermarkt_code": "IT1",
        "fbref_name": "ITA-Serie A",
        "reglas_clasificacion": {
            "champions": [1, 2, 3, 4],
            "europa": [5],
            "conference": [6],
            "descenso": [18, 19, 20],
        },
        "aliases_equipos": {
            "internazionale": "inter milan",
            "inter": "inter milan",
            "milan": "ac milan",
            "roma": "as roma",
            "lazio": "ss lazio",
            "napoli": "ssc napoli",
        },
    },
    "ligue-1": {
        "db_liga_id": 27,
        "slug": "ligue-1",
        "nombre": "Ligue 1",
        "pais": "Francia",
        "temporada": CURRENT_SEASON,
        "tipo": "domestic",
        "sofascore_tournament_id": 34,
        "sofascore_season_id": None,
        "transfermarkt_code": "FR1",
        "fbref_name": "FRA-Ligue 1",
        "reglas_clasificacion": {
            "champions": [1, 2, 3, 4],
            "europa": [5],
            "conference": [6],
            "playoff_descenso": [16],
            "descenso": [17, 18],
        },
        "aliases_equipos": {
            "stade rennais": "rennes",
            "paris s-g": "paris saint-germain",
            "paris sg": "paris saint-germain",
            "psg": "paris saint-germain",
        },
    },
    "champions-league": {
        "db_liga_id": 28,
        "slug": "champions-league",
        "nombre": "Champions League",
        "pais": "Europa",
        "temporada": CURRENT_SEASON,
        "tipo": "continental",
        "sofascore_tournament_id": 7,
        "sofascore_season_id": 76953,
        "transfermarkt_code": "CL",
        "fbref_name": None,
        "reglas_clasificacion": {
            "octavos_directos": list(range(1, 9)),
            "playoff": list(range(9, 25)),
            "eliminado": list(range(25, 37)),
        },
        "aliases_equipos": {
            "internazionale": "inter",
            "bayer leverkusen": "bayer 04 leverkusen",
            "union saint-gilloise": "royale union saint-gilloise",
            "club brugge": "club brugge kv",
            "slavia prague": "sk slavia praha",
        },
    },
    "hypermotion": {
        "db_liga_id": 33,
        "slug": "hypermotion",
        "nombre": "LaLiga Hypermotion",
        "pais": "Espana",
        "temporada": CURRENT_SEASON,
        "tipo": "domestic",
        "sofascore_tournament_id": 54,
        "sofascore_season_id": None,
        "transfermarkt_code": "ES2",
        "fbref_name": "ESP-Segunda Division",
        "reglas_clasificacion": {
            "ascenso_directo": [1, 2],
            "playoff_ascenso": [3, 4, 5, 6],
            "descenso": [19, 20, 21, 22],
        },
        "aliases_equipos": {
            "rc deportivo de la coruna": "deportivo de la coruna",
            "real sporting de gijon": "sporting gijon",
            "burgos cf": "burgos club de futbol",
            "real sociedad b": "real sociedad b u21",
        },
    },
    "portugal": {
        "db_liga_id": 37,
        "slug": "portugal",
        "nombre": "Primeira Liga",
        "pais": "Portugal",
        "temporada": CURRENT_SEASON,
        "tipo": "domestic",
        "sofascore_tournament_id": None,
        "sofascore_season_id": None,
        "transfermarkt_code": "PO1",
        "fbref_name": None,
        "reglas_clasificacion": {
            "champions": [1, 2],
            "europa": [3],
            "conference": [4],
            "playoff_descenso": [16],
            "descenso": [17, 18],
        },
        "aliases_equipos": {
            "sporting": "sporting cp",
            "sporting lisbon": "sporting cp",
            "porto": "fc porto",
            "benfica": "sl benfica",
        },
    },
    "argentina": {
        "db_liga_id": 29,
        "slug": "argentina",
        "nombre": "Liga Profesional Argentina",
        "pais": "Argentina",
        "temporada": CURRENT_SEASON,
        "tipo": "domestic",
        "sofascore_tournament_id": 155,
        "sofascore_season_id": 87913,
        "transfermarkt_code": "ARG1",
        "fbref_name": None,
        "reglas_clasificacion": {},
        "aliases_equipos": {
            "ca river plate": "river plate",
            "club atletico river plate": "river plate",
            "ca boca juniors": "boca juniors",
            "club atletico boca juniors": "boca juniors",
            "ca independiente": "independiente",
            "club atletico independiente": "independiente",
            "ca lanus": "lanus",
            "club atletico lanus": "lanus",
            "ca talleres": "talleres",
            "club atletico talleres": "talleres",
            "club atletico belgrano": "belgrano",
            "club atletico platense": "platense",
            "club atletico union de santa fe": "union de santa fe",
            "club atletico union": "union de santa fe",
            "ca union santa fe": "union de santa fe",
            "club estudiantes de la plata": "estudiantes de la plata",
            "estudiantes lp": "estudiantes de la plata",
            "gimnasia y esgrima la plata": "gimnasia y esgrima",
            "gimnasia la plata": "gimnasia y esgrima la plata",
            "newells": "newells old boys",
            "newell's old boys": "newells old boys",
            "instituto de cordoba": "instituto",
            "instituto ac cordoba": "instituto",
            "instituto acc": "instituto",
            "central cordoba": "central cordoba sde",
            "central cordoba santiago del estero": "central cordoba sde",
            "aa argentinos juniors": "argentinos juniors",
            "asociacion atletica argentinos juniors": "argentinos juniors",
            "cs independiente rivadavia": "independiente rivadavia",
            "atletico tucuman": "atletico tucuman",
            "ca tucuman": "atletico tucuman",
            "club atletico tucuman": "atletico tucuman",
            "ca san lorenzo de almagro": "san lorenzo",
            "csd defensa y justicia": "defensa y justicia",
            "ca sarmiento junin": "sarmiento",
            "ca gimnasia y esgrima mendoza": "gimnasia y esgrima mendoza",
            "ca central cordoba sde": "central cordoba sde",
            "aa estudiantes rio cuarto": "estudiantes de rio cuarto",
            "club de gimnasia y esgrima la plata": "gimnasia y esgrima",
        },
    },
    "brasil": {
        "db_liga_id": 34,
        "slug": "brasil",
        "nombre": "Brasileirao Serie A",
        "pais": "Brasil",
        "temporada": CURRENT_SEASON,
        "tipo": "domestic",
        "sofascore_tournament_id": None,
        "sofascore_season_id": None,
        "transfermarkt_code": None,
        "fbref_name": None,
        "reglas_clasificacion": {
            "libertadores": [1, 2, 3, 4],
            "libertadores_previa": [5, 6],
            "sudamericana": [7, 8, 9, 10, 11, 12],
            "descenso": [17, 18, 19, 20],
        },
        "aliases_equipos": {},
    },
    "libertadores": {
        "db_liga_id": 35,
        "slug": "libertadores",
        "nombre": "Copa Libertadores",
        "pais": "Sudamerica",
        "temporada": CURRENT_SEASON,
        "tipo": "continental",
        "sofascore_tournament_id": None,
        "sofascore_season_id": None,
        "transfermarkt_code": None,
        "fbref_name": None,
        "reglas_clasificacion": {
            "fase_grupos": [],
            "octavos": [],
            "cuartos": [],
            "semifinales": [],
            "final": [],
        },
        "aliases_equipos": {},
    },
}


def get_league(slug: str) -> dict:
    """Return a league config by slug."""
    return LEAGUES[slug]


def get_league_by_db_id(db_liga_id: int) -> dict | None:
    """Return the first league config matching a Supabase liga id."""
    return next(
        (league for league in LEAGUES.values() if league["db_liga_id"] == db_liga_id),
        None,
    )
